"""
PyTorch Training Script for Driver Safety AI.
Trains DriverSafetyNet on sequence datasets using AdamW, class-weighted CrossEntropyLoss,
early stopping, and saves checkpoint with complete provenance metadata.
"""

import os
import glob
import time
import random
import json
import argparse
import pickle
import numpy as np
import pandas as pd
from typing import Dict, Any, Tuple, List, Optional

import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import f1_score, accuracy_score
import yaml

from src.utils.paths import MODEL_PATH, SCALER_PATH, RAW_DATA_DIR, PROCESSED_DATA_DIR, load_config
from src.features.temporal_features import TemporalFeatureExtractor
from src.model.driver_safety_net import DriverSafetyNet
from src.data.dataset import prepare_subject_split_dataset, DriverSafetyDataset

def set_seed(seed: int = 42):
    """Ensure exact reproducibility across PyTorch, Numpy, Python."""
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

def train_one_epoch(
    model: nn.Module,
    dataloader: DataLoader,
    criterion: nn.Module,
    optimizer: torch.optim.Optimizer,
    device: torch.device
) -> Tuple[float, float]:
    """Train for one epoch and return average loss and accuracy."""
    model.train()
    running_loss = 0.0
    correct = 0
    total = 0

    for inputs, targets in dataloader:
        inputs, targets = inputs.to(device), targets.to(device)

        optimizer.zero_grad()
        outputs = model(inputs) # Raw logits
        loss = criterion(outputs, targets)
        loss.backward()

        # Gradient clipping for LSTM stability
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()

        running_loss += loss.item() * inputs.size(0)
        _, preds = torch.max(outputs, 1)
        correct += (preds == targets).sum().item()
        total += targets.size(0)

    epoch_loss = running_loss / max(total, 1)
    epoch_acc = correct / max(total, 1)
    return epoch_loss, epoch_acc

def evaluate_epoch(
    model: nn.Module,
    dataloader: DataLoader,
    criterion: nn.Module,
    device: torch.device
) -> Tuple[float, float, float]:
    """Evaluate on validation set and return loss, accuracy, and Macro F1 score."""
    model.eval()
    running_loss = 0.0
    all_preds = []
    all_targets = []

    with torch.no_grad():
        for inputs, targets in dataloader:
            inputs, targets = inputs.to(device), targets.to(device)
            outputs = model(inputs)
            loss = criterion(outputs, targets)

            running_loss += loss.item() * inputs.size(0)
            _, preds = torch.max(outputs, 1)

            all_preds.extend(preds.cpu().numpy())
            all_targets.extend(targets.cpu().numpy())

    total = len(all_targets)
    val_loss = running_loss / max(total, 1)
    val_acc = float(accuracy_score(all_targets, all_preds)) if total > 0 else 0.0
    val_f1 = float(f1_score(all_targets, all_preds, average="macro")) if total > 0 else 0.0

    return val_loss, val_acc, val_f1

def train_from_processed_split(
    proc_dir: str = "data/processed/proposed_12feature",
    config_path: str = "configs/proposed_12feature.yaml",
    save_path: str = "outputs/models/best_driver_safety_net.pt",
    scaler_save_path: str = "outputs/models/scaler_proposed_12feature.pkl"
) -> Dict[str, Any]:
    """
    Trains DriverSafetyNet directly using participant-isolated numpy splits generated by dataset_builder.
    Fits scaler exclusively on train_x to prevent data leakage.
    """
    with open(config_path, "r") as f:
        config = yaml.safe_load(f)

    set_seed(config.get("training", {}).get("seed", 42))
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    tr_x_path = os.path.join(proc_dir, "train_x.npy")
    tr_y_path = os.path.join(proc_dir, "train_y.npy")
    val_x_path = os.path.join(proc_dir, "val_x.npy")
    val_y_path = os.path.join(proc_dir, "val_y.npy")

    if not os.path.exists(tr_x_path):
        raise FileNotFoundError(f"Processed training split '{tr_x_path}' not found. Run dataset_builder first.")

    tr_x = np.load(tr_x_path)
    tr_y = np.load(tr_y_path)
    val_x = np.load(val_x_path)
    val_y = np.load(val_y_path)

    print("\n==================================================================")
    print("   DRIVER SAFETY AI - PROPOSED 12-FEATURE MODEL TRAINING          ")
    print("==================================================================")
    print(f" Operating Device : {device}")
    print(f" Train Split Shape: {tr_x.shape}")
    print(f" Val Split Shape  : {val_x.shape}")
    print(f" Model Output Path: {save_path}")
    print("==================================================================\n")

    # Fit scaler ONLY on train_x to prevent leakage
    N_tr, T, C = tr_x.shape
    N_val = val_x.shape[0]

    scaler = StandardScaler()
    tr_x_flat = tr_x.reshape(-1, C)
    tr_x_scaled_flat = scaler.fit_transform(tr_x_flat)
    tr_x_scaled = tr_x_scaled_flat.reshape(N_tr, T, C)

    val_x_flat = val_x.reshape(-1, C)
    val_x_scaled_flat = scaler.transform(val_x_flat)
    val_x_scaled = val_x_scaled_flat.reshape(N_val, T, C)

    os.makedirs(os.path.dirname(scaler_save_path), exist_ok=True)
    with open(scaler_save_path, "wb") as f:
        pickle.dump(scaler, f)

    # Compute class weights
    classes, counts = np.unique(tr_y, return_counts=True)
    weights = len(tr_y) / (len(classes) * counts.astype(np.float32))
    class_weights = torch.tensor(weights, dtype=torch.float32).to(device)

    # Build PyTorch DataLoaders
    train_tensor_x = torch.tensor(tr_x_scaled, dtype=torch.float32)
    train_tensor_y = torch.tensor(tr_y, dtype=torch.long)
    val_tensor_x = torch.tensor(val_x_scaled, dtype=torch.float32)
    val_tensor_y = torch.tensor(val_y, dtype=torch.long)

    batch_size = config.get("training", {}).get("batch_size", 32)
    train_loader = DataLoader(TensorDataset(train_tensor_x, train_tensor_y), batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(TensorDataset(val_tensor_x, val_tensor_y), batch_size=batch_size, shuffle=False)

    # Initialize DriverSafetyNet
    model = DriverSafetyNet(
        in_channels=config["model"]["in_channels"],
        cnn_filters=config["model"]["cnn_filters"],
        kernel_size=config["model"]["kernel_size"],
        lstm_hidden_size=config["model"]["lstm_hidden_size"],
        lstm_num_layers=config["model"]["lstm_num_layers"],
        lstm_bidirectional=config["model"]["lstm_bidirectional"],
        dropout=config["model"]["dropout"],
        num_classes=config["model"]["num_classes"]
    ).to(device)

    criterion = nn.CrossEntropyLoss(weight=class_weights)
    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=config.get("training", {}).get("learning_rate", 0.001),
        weight_decay=config.get("training", {}).get("weight_decay", 1e-4)
    )
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, mode="min", factor=0.5, patience=5
    )

    train_losses, val_losses = [], []
    train_accs, val_accs = [], []
    best_val_loss = float("inf")
    best_val_f1 = 0.0
    patience_counter = 0
    best_epoch = 0

    epochs = config.get("training", {}).get("epochs", 30)
    patience = config.get("training", {}).get("early_stopping_patience", 7)

    print(f"[Training] Starting training loop for {epochs} epochs...")
    for epoch in range(1, epochs + 1):
        t0 = time.time()
        train_loss, train_acc = train_one_epoch(model, train_loader, criterion, optimizer, device)
        val_loss, val_acc, val_f1 = evaluate_epoch(model, val_loader, criterion, device)
        scheduler.step(val_loss)
        elapsed = time.time() - t0

        train_losses.append(train_loss)
        val_losses.append(val_loss)
        train_accs.append(train_acc)
        val_accs.append(val_acc)

        print(
            f"Epoch {epoch:02d}/{epochs:02d} [{elapsed:.1f}s] - "
            f"Train Loss: {train_loss:.4f} Acc: {train_acc:.4f} | "
            f"Val Loss: {val_loss:.4f} Acc: {val_acc:.4f} F1: {val_f1:.4f}"
        )

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            best_val_f1 = val_f1
            best_epoch = epoch
            patience_counter = 0

            checkpoint = {
                "model_state_dict": model.state_dict(),
                "class_names": config["classes"]["names"],
                "feature_names": TemporalFeatureExtractor.FEATURE_NAMES,
                "window_size": config["features"]["window_size"],
                "model_config": config["model"],
                "scaler_path": scaler_save_path,
                "best_epoch": best_epoch,
                "best_val_loss": best_val_loss,
                "best_val_f1": best_val_f1,
                "train_losses": train_losses,
                "val_losses": val_losses,
                "train_accs": train_accs,
                "val_accs": val_accs,
                "device": str(device),
                "timestamp": time.strftime("%Y-%m-%d %H:%M:%S")
            }
            os.makedirs(os.path.dirname(save_path), exist_ok=True)
            torch.save(checkpoint, save_path)
            print(f" --> Saved best checkpoint to {save_path} (Val Loss: {val_loss:.4f})")
        else:
            patience_counter += 1
            if patience_counter >= patience:
                print(f"[Training] Early stopping triggered at epoch {epoch}.")
                break

    return {
        "train_losses": train_losses,
        "val_losses": val_losses,
        "train_accs": train_accs,
        "val_accs": val_accs,
        "best_epoch": best_epoch,
        "best_val_loss": best_val_loss,
        "best_val_f1": best_val_f1,
        "model_path": save_path
    }

def main():
    parser = argparse.ArgumentParser(description="Driver Safety AI Model Training Script")
    parser.add_argument("--config", type=str, default="configs/proposed_12feature.yaml", help="Path to config file")
    parser.add_argument("--proc-dir", type=str, default="data/processed/proposed_12feature", help="Path to processed split directory")
    parser.add_argument("--save-path", type=str, default="outputs/models/best_driver_safety_net.pt", help="Path to save checkpoint")
    args = parser.parse_args()

    train_from_processed_split(
        proc_dir=args.proc_dir,
        config_path=args.config,
        save_path=args.save_path
    )

if __name__ == "__main__":
    main()
